version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update && apt-get install jq
  build:
    commands:
      - cd ingest-orig && /bin/bash aws-deploy/deploy.sh
artifacts:
  files:
    - ingest-orig/aws-deploy/infrastructure.yml

